import { describe, expect, it } from 'vitest';
import {
  getCompanyMonthlyBreakdown,
  getEmployeeDebtSnapshot,
  getEmployeeLifetimeStats,
  getEmployeeStats,
} from './payroll';
import type { Employee, EmployeeRateHistory, Payment, Shift } from './types';

const employees: Employee[] = [
  {
    id: 'employee-1',
    userId: 'owner-1',
    organizationId: 'org-1',
    profileId: 'profile-1',
    authUserId: 'auth-1',
    workEmail: 'e1@example.com',
    status: 'active',
    createdByProfileId: 'owner-profile',
    isOwner: false,
    hiredAt: '2025-01-01',
    terminatedAt: null,
    name: 'Nikita',
    dailyRate: 2500,
    archived: false,
    archivedAt: null,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'employee-2',
    userId: 'owner-1',
    organizationId: 'org-1',
    profileId: 'profile-2',
    authUserId: 'auth-2',
    workEmail: 'e2@example.com',
    status: 'active',
    createdByProfileId: 'owner-profile',
    isOwner: false,
    hiredAt: '2025-01-01',
    terminatedAt: null,
    name: 'Pavel',
    dailyRate: 2800,
    archived: false,
    archivedAt: null,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
];

const rateHistory: EmployeeRateHistory[] = [
  {
    id: 'rate-1',
    employeeId: 'employee-1',
    organizationId: 'org-1',
    rate: 2500,
    validFrom: '2025-01-01',
    validTo: '2025-01-31',
    createdByProfileId: 'owner-profile',
    createdAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'rate-2',
    employeeId: 'employee-1',
    organizationId: 'org-1',
    rate: 3000,
    validFrom: '2025-02-01',
    validTo: null,
    createdByProfileId: 'owner-profile',
    createdAt: '2025-02-01T00:00:00.000Z',
  },
];

const shifts: Shift[] = [
  {
    id: 'shift-1',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    date: '2025-01-03',
    status: 'shift',
    requestedStatus: 'shift',
    approvedStatus: 'shift',
    actualStatus: 'shift',
    rateSnapshot: 0,
    createdByProfileId: 'profile-1',
    requestedByProfileId: 'profile-1',
    approvedByProfileId: 'owner-profile',
    actualByProfileId: 'owner-profile',
    createdAt: '2025-01-03T00:00:00.000Z',
    updatedAt: '2025-01-03T00:00:00.000Z',
  },
  {
    id: 'shift-2',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    date: '2025-01-05',
    status: 'shift',
    requestedStatus: 'shift',
    approvedStatus: 'shift',
    actualStatus: 'shift',
    rateSnapshot: 0,
    createdByProfileId: 'profile-1',
    requestedByProfileId: 'profile-1',
    approvedByProfileId: 'owner-profile',
    actualByProfileId: 'owner-profile',
    createdAt: '2025-01-05T00:00:00.000Z',
    updatedAt: '2025-01-05T00:00:00.000Z',
  },
  {
    id: 'shift-3',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-2',
    date: '2024-12-28',
    status: 'shift',
    requestedStatus: 'shift',
    approvedStatus: 'shift',
    actualStatus: 'shift',
    rateSnapshot: 2800,
    createdByProfileId: 'profile-2',
    requestedByProfileId: 'profile-2',
    approvedByProfileId: 'owner-profile',
    actualByProfileId: 'owner-profile',
    createdAt: '2024-12-28T00:00:00.000Z',
    updatedAt: '2024-12-28T00:00:00.000Z',
  },
  {
    id: 'shift-4',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    date: '2099-01-10',
    status: 'shift',
    requestedStatus: 'shift',
    approvedStatus: 'shift',
    actualStatus: null,
    rateSnapshot: 3000,
    createdByProfileId: 'owner-profile',
    requestedByProfileId: 'owner-profile',
    approvedByProfileId: 'owner-profile',
    actualByProfileId: null,
    createdAt: '2099-01-10T00:00:00.000Z',
    updatedAt: '2099-01-10T00:00:00.000Z',
  },
  {
    id: 'shift-5',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    date: '2025-01-11',
    status: 'sick_leave',
    requestedStatus: 'sick_leave',
    approvedStatus: 'sick_leave',
    actualStatus: null,
    rateSnapshot: 2500,
    createdByProfileId: 'profile-1',
    requestedByProfileId: 'profile-1',
    approvedByProfileId: 'owner-profile',
    actualByProfileId: null,
    createdAt: '2025-01-11T00:00:00.000Z',
    updatedAt: '2025-01-11T00:00:00.000Z',
  },
  {
    id: 'shift-6',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    date: '2025-01-12',
    status: 'day_off',
    requestedStatus: 'day_off',
    approvedStatus: 'day_off',
    actualStatus: null,
    rateSnapshot: 2500,
    createdByProfileId: 'profile-1',
    requestedByProfileId: 'profile-1',
    approvedByProfileId: 'owner-profile',
    actualByProfileId: null,
    createdAt: '2025-01-12T00:00:00.000Z',
    updatedAt: '2025-01-12T00:00:00.000Z',
  },
  {
    id: 'shift-7',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    date: '2025-02-05',
    status: 'shift',
    requestedStatus: 'shift',
    approvedStatus: 'shift',
    actualStatus: 'shift',
    rateSnapshot: 0,
    createdByProfileId: 'profile-1',
    requestedByProfileId: 'profile-1',
    approvedByProfileId: 'owner-profile',
    actualByProfileId: 'owner-profile',
    createdAt: '2025-02-05T00:00:00.000Z',
    updatedAt: '2025-02-05T00:00:00.000Z',
  },
  {
    id: 'shift-8',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    date: '2025-02-20',
    status: 'shift',
    requestedStatus: 'shift',
    approvedStatus: 'shift',
    actualStatus: null,
    rateSnapshot: 3000,
    createdByProfileId: 'owner-profile',
    requestedByProfileId: 'owner-profile',
    approvedByProfileId: 'owner-profile',
    actualByProfileId: null,
    createdAt: '2025-02-20T00:00:00.000Z',
    updatedAt: '2025-02-20T00:00:00.000Z',
  },
];

const payments: Payment[] = [
  {
    id: 'payment-1',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    amount: 3000,
    date: '2025-01-10',
    comment: 'Advance',
    status: 'approved',
    requestedByAuthUserId: 'auth-owner',
    approvedByAuthUserId: 'auth-owner',
    requestedByProfileId: 'owner-profile',
    approvedByProfileId: 'owner-profile',
    approvedAt: '2025-01-10T00:00:00.000Z',
    editedByAdmin: false,
    createdAt: '2025-01-10T00:00:00.000Z',
    updatedAt: '2025-01-10T00:00:00.000Z',
  },
  {
    id: 'payment-2',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-2',
    amount: 1000,
    date: '2024-12-30',
    comment: 'Partial payment',
    status: 'approved',
    requestedByAuthUserId: 'auth-owner',
    approvedByAuthUserId: 'auth-owner',
    requestedByProfileId: 'owner-profile',
    approvedByProfileId: 'owner-profile',
    approvedAt: '2024-12-30T00:00:00.000Z',
    editedByAdmin: false,
    createdAt: '2024-12-30T00:00:00.000Z',
    updatedAt: '2024-12-30T00:00:00.000Z',
  },
  {
    id: 'payment-3',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    amount: 600,
    date: '2025-01-09',
    comment: 'Pending employee claim',
    status: 'pending',
    requestedByAuthUserId: 'auth-1',
    approvedByAuthUserId: null,
    requestedByProfileId: 'profile-1',
    approvedByProfileId: null,
    approvedAt: null,
    editedByAdmin: false,
    createdAt: '2025-01-09T00:00:00.000Z',
    updatedAt: '2025-01-09T00:00:00.000Z',
  },
  {
    id: 'payment-4',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    amount: 700,
    date: '2025-02-06',
    comment: 'Rejected correction',
    status: 'rejected',
    requestedByAuthUserId: 'auth-owner',
    approvedByAuthUserId: null,
    requestedByProfileId: 'owner-profile',
    approvedByProfileId: null,
    approvedAt: null,
    editedByAdmin: false,
    createdAt: '2025-02-06T00:00:00.000Z',
    updatedAt: '2025-02-06T00:00:00.000Z',
  },
  {
    id: 'payment-5',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    amount: 800,
    date: '2025-02-07',
    comment: 'Pending payout',
    status: 'pending',
    requestedByAuthUserId: 'auth-1',
    approvedByAuthUserId: null,
    requestedByProfileId: 'profile-1',
    approvedByProfileId: null,
    approvedAt: null,
    editedByAdmin: false,
    createdAt: '2025-02-07T00:00:00.000Z',
    updatedAt: '2025-02-07T00:00:00.000Z',
  },
  {
    id: 'payment-6',
    userId: 'owner-1',
    organizationId: 'org-1',
    employeeId: 'employee-1',
    amount: 900,
    date: '2025-03-01',
    comment: 'Future payout',
    status: 'approved',
    requestedByAuthUserId: 'auth-owner',
    approvedByAuthUserId: 'auth-owner',
    requestedByProfileId: 'owner-profile',
    approvedByProfileId: 'owner-profile',
    approvedAt: '2025-03-01T00:00:00.000Z',
    editedByAdmin: false,
    createdAt: '2025-03-01T00:00:00.000Z',
    updatedAt: '2025-03-01T00:00:00.000Z',
  },
];

const source = { employees, rateHistory, shifts, payments };

describe('payroll domain', () => {
  it('calculates monthly stats with canonical statuses', () => {
    expect(getEmployeeStats(source, 'employee-1', 1, 2025)).toEqual({
      workedCount: 2,
      plannedCount: 0,
      sickCount: 1,
      dayOffCount: 1,
      earnedActual: 5000,
      paidApproved: 3000,
      dueNow: 2000,
      forecastTotal: 5000,
    });
  });

  it('calculates lifetime stats with approved payments only', () => {
    expect(getEmployeeLifetimeStats(source, 'employee-2')).toEqual({
      workedCount: 1,
      plannedCount: 0,
      sickCount: 0,
      dayOffCount: 0,
      earnedActual: 2800,
      paidApproved: 1000,
      dueNow: 1800,
      forecastTotal: 2800,
    });
  });

  it('includes future approved shifts in forecast_total', () => {
    expect(getEmployeeStats(source, 'employee-1', 1, 2099)).toEqual({
      workedCount: 0,
      plannedCount: 1,
      sickCount: 0,
      dayOffCount: 0,
      earnedActual: 0,
      paidApproved: 0,
      dueNow: 0,
      forecastTotal: 3000,
    });
  });

  it('carries opening balance into company monthly breakdown', () => {
    const breakdown = getCompanyMonthlyBreakdown(source, 2025);

    expect(breakdown[0]).toEqual({
      month: 1,
      workedCount: 2,
      sickCount: 1,
      dayOffCount: 1,
      earnedActual: 5000,
      paidApproved: 3000,
      forecastTotal: 5000,
      delta: 2000,
      balanceEnd: 3800,
    });
  });

  it('builds debt snapshot as of today with pending payments and historical rates', () => {
    expect(getEmployeeDebtSnapshot(source, 'employee-1', '2025-02-10')).toEqual({
      workedCountTotalToDate: 3,
      workedCountCurrentMonthToDate: 1,
      accruedToDate: 8000,
      paidToDate: 4400,
      debtToDate: 3600,
    });
  });
});
